#if !canImport(ObjectiveC)
import XCTest

extension SwiftDirectorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftDirectorTests = [
        ("testAuthBind", testAuthBind),
        ("testBind", testBind),
        ("testConnect", testConnect),
        ("testConnectionReconnect", testConnectionReconnect),
        ("testDuplicate", testDuplicate),
        ("testSearch", testSearch),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftDirectorTests.__allTests__SwiftDirectorTests),
    ]
}
#endif
